services:
  postgres:
    image: postgres:latest
    container_name: postgres_2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salad123
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
